
/* USER AUTHENTICATION */
const SERVER = {
  CONNECTION_FAIL:'la connexion au serveur a était échoué'
};

const SIDEBAR = {
    HIDE:'HIDE',
    SHOW:'SHOW'
};


const AUTHENTICATION = {
    AUTH: 'AUTH_LOAD',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    LOGGED : 'LOGGED'
};

/* GET CV */
const GET_CV = {
    LOAD: 'LOAD_CV',
    LOAD_SUCCESS: 'LOAD_CV_SUCCESS',
    LOAD_FAIL: 'LOAD_CV_FAIL'
};

/* GET CV */
const GET_ATTESTATION = {
    LOAD: 'LOAD_ATTESTATION',
    LOAD_SUCCESS: 'LOAD_ATTESTATION_SUCCESS',
    LOAD_FAIL: 'LOAD_ATTESTATION_FAIL'
};

/* DEMANDS LIST */
const DEMANDS = {
    LOAD: 'DEMANDS_LOAD',
    LOAD_SUCCESS: 'DEMANDS_LOAD_SUCCESS',
    LOAD_FAIL: 'DEMANDS_LOAD_FAIL'
};

/* GET INTERNSHIPS ACCEPTED LIST */
const INTERNSHIPS_ACCEPTED = {
    LOAD: 'INTERNSHIPS_ACCEPTED_LIST_LOAD',
    LOAD_SUCCESS: 'INTERNSHIPS_ACCEPTED_LIST_SUCCESS',
    LOAD_FAIL: 'INTERNSHIPS_LOAD_FAIL'
};

/* REFUSED DEMAND  LIST */
const DEMANDS_REFUSED = {
    LOAD: 'DEMANDS_REFUSED_LOAD',
    LOAD_SUCCESS: 'DEMANDS_REFUSED_SUCCESS',
    LOAD_FAIL: 'DEMANDS_REFUSED_FAIL'
};

/* COMPLETED INTERNSHIPS  LIST */
const COMPLETED_INTERNSHIPS = {
    LOAD: 'COMPLETED_INTERNSHIPS_LOAD',
    LOAD_SUCCESS: 'COMPLETED_INTERNSHIPS_SUCCESS',
    LOAD_FAIL: 'COMPLETED_INTERNSHIPS_FAIL'
};

/* CLOSED INTERNSHIPS  LIST */
const CLOSED_INTERNSHIPS = {
    LOAD: 'CLOSED_INTERNSHIPS_LOAD',
    LOAD_SUCCESS: 'CLOSED_INTERNSHIPS_SUCCESS',
    LOAD_FAIL: 'CLOSED_INTERNSHIPS_FAIL'
};

/* DETAILS INTERNSHIP   */
const DETAILS_INTERNSHIP = {
    LOAD: 'DETAILS_INTERNSHIP_LOAD',
    LOAD_SUCCESS: 'DETAILS_INTERNSHIP_SUCCESS',
    LOAD_FAIL: 'DETAILS_INTERNSHIP_FAIL'
};


/* GET DEMAND  */
const DEMAND = {
    LOAD: 'DEMAND_LOAD',
    LOAD_SUCCESS: 'DEMAND_LOAD_SUCCESS',
    LOAD_FAIL: 'DEMAND_LOAD_FAIL'
};

/* ADD DEMAND */
const ADD_DEMAND = {
    ADD: 'ADD_DEMAND_LOAD',
    ADD_SUCCESS: 'ADD_DEMAND_SUCCESS',
    ADD_FAIL: 'ADD_DEMAND_FAIL'
};

/* REFUSED DEMAND */
const REFUSED_DEMAND = {
    REFUSED: 'REFUSED_DEMAND_LOAD',
    REFUSED_SUCCESS: 'REFUSED_DEMAND_SUCCESS',
    REFUSED_FAIL: 'REFUSED_DEMAND_FAIL'
};


/* ACCEPT DEMAND */
const ACCEPT_DEMAND = {
    ACCEPT: 'ACCEPT_DEMAND_LOAD',
    ACCEPT_SUCCESS: 'ACCEPT_DEMAND_SUCCESS',
    ACCEPT_FAIL: 'ACCEPT_DEMAND_FAIL'
};

/* CLOSE DEMAND */
const CLOSE_INTERNSHIP = {
    CLOSE: 'CLOSE_INTERNSHIP_LOAD',
    CLOSE_SUCCESS: 'CLOSE_INTERNSHIP_SUCCESS',
    CLOSE_FAIL: 'CLOSE_INTERNSHIP_FAIL'
};

/* DELETE DEMAND */
const DELETE_DEMAND = {
    DELETE : 'DELETE_DEMAND_LOAD',
    DELETE_SUCCESS : 'DELETE_DEMAND_SUCCESS',
    DELETE_FAIL : 'DELETE_DEMAND_FAIL',
};


/* SUPERVISOR */
const SUPERVISORS = {
    LOAD: 'SUPERVISORS_LOAD',
    LOAD_SUCCESS: 'SUPERVISORS_LOAD_SUCCESS',
    LOAD_FAIL: 'SUPERVISORS_LOAD_FAIL'
};

/* ADD SUPERVISOR */
const ADD_SUPERVISOR = {
    ADD : 'ADD_SUPERVISOR',
    ADD_SUCCESS : 'ADD_SUPERVISOR_SUCCESS',
    ADD_FAIL : 'ADD_SUPERVISOR_FAIL'
};

/* UPDATE SUPERVISOR */
const UPDATE_SUPERVISOR = {
    UPDATE : 'UPDATE_SUPERVISOR',
    UPDATE_SUCCESS : 'UPDATE_SUPERVISOR_SUCCESS',
    UPDATE_FAIL : 'UPDATE_SUPERVISOR_FAIL'
};

/* DELETE SUPERVISOR */
const DELETE_SUPERVISOR = {
    DELETE : 'DELETE_SUPERVISOR',
    DELETE_SUCCESS : 'DELETE_SUPERVISOR_SUCCESS',
    DELETE_FAIL : 'DELETE_SUPERVISOR_FAIL'
};

/* GET SUPERVISOR */
const GET_SUPERVISOR = {
    LOAD: 'SUPERVISOR_LOAD',
    LOAD_SUCCESS: 'SUPERVISOR_LOAD_SUCCESS',
    LOAD_FAIL: 'SUPERVISOR_LOAD_FAIL'
};

/* DETAILS TRAINEE   */
const DETAILS_TRAINEE = {
    LOAD: 'DETAILS_TRAINEE_LOAD',
    LOAD_SUCCESS: 'DETAILS_TRAINEE_SUCCESS',
    LOAD_FAIL: 'DETAILS_TRAINEE_FAIL'
};


/* GET TRAINEE */
const GET_TRAINEE = {
    LOAD: 'TRAINEE_LOAD',
    LOAD_SUCCESS: 'TRAINEE_LOAD_SUCCESS',
    LOAD_FAIL: 'TRAINEE_LOAD_FAIL'
};


/* UPDATE TRAINEE */
const UPDATE_TRAINEE = {
    UPDATE: 'UPDATE_TRAINEE_LOAD',
    UPDATE_SUCCESS: 'UPDATE_TRAINEE_SUCCESS',
    UPDATE_FAIL: 'UPDATE_TRAINEE_FAIL'
};

/* TRAINEE LIST */
const TRAINEES = {
    LOAD: 'TRAINEES_LOAD',
    LOAD_SUCCESS: 'TRAINEES_LOAD_SUCCESS',
    LOAD_FAIL: 'TRAINEES_LOAD_FAIL'
};

/* MESSAGE  */
const MESSAGE = {
    LOAD_MESSAGE : "MESSAGE_LOAD",
    MESSAGE : "MESSAGE",
    MESSAGE_FAIL : "MESSAGE_FAIL",
    MESSAGE_SUCCESS : "MESSAGE_SUCCESS",
    MESSAGE_ERROR : "MESSAGE_ERROR"
};

/* SEARCH */
const SEARCH = {
    SEARCH_LOAD : "SEARCH_LOAD",
    SEARCH_SUCCESS : "SEARCH_SUCCESS",
    SEARCH_FAIL : "SEARCH_FAIL"
};


const COUNT_TRAINEES = {
    LOAD: 'COUNT_TRAINEES_LOAD',
    LOAD_SUCCESS: 'COUNT_TRAINEES_LOAD_SUCCESS',
    LOAD_FAIL: 'COUNT_TRAINEES_LOAD_FAIL'
};

export {SIDEBAR,COUNT_TRAINEES,SERVER,AUTHENTICATION,GET_CV,INTERNSHIPS_ACCEPTED,DEMANDS_REFUSED, DEMANDS,CLOSED_INTERNSHIPS,COMPLETED_INTERNSHIPS, DEMAND, ADD_DEMAND, DELETE_DEMAND,
    ACCEPT_DEMAND, CLOSE_INTERNSHIP, UPDATE_TRAINEE,GET_SUPERVISOR,DELETE_SUPERVISOR, REFUSED_DEMAND, ADD_SUPERVISOR,
    SUPERVISORS,UPDATE_SUPERVISOR, GET_TRAINEE,TRAINEES, DETAILS_TRAINEE, DETAILS_INTERNSHIP, MESSAGE , SEARCH, GET_ATTESTATION };